DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS post cascade;
DROP TABLE IF EXISTS comment cascade;
DROP TABLE IF EXISTS email cascade;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  body2 TEXT NOT NULL,
  pris TEXT NOT NULL,
  file TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE comment(
	commentid SERIAL PRIMARY KEY,
	postid INTEGER NOT NULL,
	cAuthor_id INTEGER NOT NULL,
	cCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	commenttext TEXT NOT NULL,
	FOREIGN KEY (cAuthor_id) REFERENCES users (id),
	FOREIGN KEY (postid) REFERENCES  post (id)
);

CREATE TABLE email(
	uid INTEGER PRIMARY KEY,
	mail TEXT UNIQUE NOT NULL,
	FOREIGN KEY (uid) REFERENCES users (id)
);