DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS email;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  body2 TEXT NOT NULL,
  pris TEXT NOT NULL,
  file TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE comment(
	commentid INTEGER PRIMARY KEY AUTOINCREMENT,
	postid INTEGER NOT NULL,
	cAuthor_id INTEGER NOT NULL,
	cCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	commenttext TEXT NOT NULL,
	FOREIGN KEY (cAuthor_id) REFERENCES user (id),
	FOREIGN KEY (postid) REFERENCES  post (id)
);

CREATE TABLE email(
	uid INTEGER PRIMARY KEY,
	mail TEXT UNIQUE NOT NULL,
  eCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (uid) REFERENCES user (id)
);